In [ ]:
4 #데이터 정의
months=['Jan','Feb','Mar','April','May','June','July','Agust','Sep','Oct','November','December']
rainfall=['30','' ]

8 #



23 # y축 범위 설정 (0부터 시작하여 최대값보다 약간 더 높게)
plt.ylim(0,max(rainfall)*1.1)

26 # 데이터 포인트에 값 표시
for i. value in enumerate(rainfall):
    plt.text(i,value+10,str(value), ha='center',va='bottom')

30 #레이아웃 조정
plt.tight_layout()

33 #그래프 표시
plt.show()

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [4]:
pip install numpy

In [5]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [7]:
c=[1,2,3]

In [8]:
type(c)

list

In [10]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])       # 첫 번째 요소
print(arr[-1])      # 마지막 요소
print(arr[1:4])     # 1~3번 인덱스 값

10
50
[20 30 40]


In [11]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

print(matrix[0, 1])      # 첫 번째 행, 두 번째 열
print(matrix[1:])        # 두 번째 행 이후 모두

2
[[3 4]
 [5 6]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)         # [11 22 33]
print(a * b)         # [10 40 90]
print(a ** 2)        # 제곱 [1 4 9]
print(np.sqrt(a))    # 제곱근

[11 22 33]
[10 40 90]
[1 4 9]
[1.         1.41421356 1.73205081]


In [12]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Min/Max:", np.min(arr), np.max(arr))

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Min/Max: 1 5


In [13]:
arr = np.array([1, 2, 3])
print(arr + 10)  # 모든 원소에 10 더하기

[11 12 13]


In [14]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 30])  # 30보다 큰 요소만, 조건달기

[40 50]


In [15]:
# 실습문제 1.다음 조건에 맞는 배열을 생성하고 출력하세요.
# 1차원 배열, 5개의 요소, 0으로 초기화된 배열

import numpy as np

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [16]:
# 실습문제 2.1부터 10까지의 숫자 중 짝수만 포함하는 배열을 생성하세요.

arr=np.arange(2,11,2)
print(arr)

[ 2  4  6  8 10]


In [17]:
# 실습문제 3. [2, 4, 6] 배열과 [10, 20, 30] 배열을 각각 생성하고, 곱셈 연산을 수행한 결과를 출력하세요.

a= np.array([2,4,6])
b= np.array([10,20,30])

print(a*b)

[ 20  80 180]


In [20]:
# 실습문제 4. 위 배열에서 20보다 큰 요소만 필터링해서 출력하세요.

a= np.array([2,4,6])
b= np.array([10,20,30])

result=a*b
print(a*b)

filtered=result[result>20]
print(filtered)

[ 20  80 180]
[ 80 180]


In [ ]:
#### Pandas ####

In [22]:
import pandas as pd

print(pd.__version__)

2.2.2


pandas에는 series 와 dataframe이 존재
주로 series를 사용

In [23]:
# dataframe 생성
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [57]:
df = pd.read_csv('/titanic.csv)
print(df.head())

SyntaxError: unterminated string literal (detected at line 1) (<ipython-input-57-64a1cf033992>, line 1)

In [34]:
df.to_csv('/titanic.csv', index=False)

In [39]:
df = pd.read_csv('/titanic.csv')

result=df.groupby('Sex')['Age'].count()
print(result)

Sex
0    843
1    466
Name: Age, dtype: int64


In [56]:
df = pd.read_csv('/titanic.csv')
df

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [52]:
df = pd.read_csv('/titanic.csv')
df['Age']

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ... 
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [48]:
df = pd.read_csv('/titanic.csv')
print(df[df['Age']>30])

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1               2  38.0   71.2833    1      1     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
6               7  54.0   51.8625    0      0     0       0       0       0   
11             12  58.0   26.5500    1      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1295         1296  43.0   27.7208    0      1     0       0       0       0   
1298         1299  50.0  211.5000    0      1     0       0       0       0   
1302         1303  37.0   90.0000    1      1     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclas

In [63]:
df = pd.read_csv('/titanic.csv')
df.dropna() # 결측치: 결함이 있는 데이터 (ex.비어있는 데이터)

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1307 rows x 28 columns]

In [64]:
df = pd.read_csv('/titanic.csv')
result = df.groupby('Sex')['Age'].mean()
print(result)

Sex
0    30.017888
1    28.572082
Name: Age, dtype: float64
